IOC_TOP = /reg/g/pcds/epics/ioc/common/ads-ioc/v0.1.5
IOC_INSTANCE_PATH := $(shell pwd)

PROJECT_NAME = Tc3EventLogger_ListenerSample
PROJECT_PATH := ../../Tc3EventLogger_ListenerSample.tsproj
PLC = Publisher

PYTMC_OPTS = 
PREFIX = PREFIX:

include $(IOC_TOP)/iocBoot/templates/Makefile.base
